// Theme Presets & Color Systems for Kısaltıcı
// Contains 5 Free themes and 10 Pro themes supporting Dark and Light mode

export const COLOR_THEMES = {
  // FREE THEMES (5)
  default: {
    id: 'default',
    nameKey: 'themeLimeName',
    nameFallback: 'Lime',
    isPro: false,
    effect: null,
    preview: {
      accent: '#DEFF36',
      bg: '#000000',
      surface: '#161616',
      header: '#090909',
      sidebar: '#0b0b0b',
      border: '#242424',
    },
    colors: {
      dark: {
        '--accent-color': '#DEFF36',
        '--accent-hover': '#cbe82e',
        '--action-btn-bg': '#DEFF36',
        '--action-btn-text': '#080a11',
        '--bg-color': '#000000',
        '--header-bg': '#090909',
        '--header-border': '#1f1f1f',
        '--sidebar-bg': '#0b0b0b',
        '--sidebar-border': '#1f1f1f',
        '--surface-bg': '#161616',
        '--surface-border': '#242424',
        '--input-bg': '#181818',
        '--input-border': '#282828',
        '--badge-bg': '#1e1e1e',
        '--badge-border': '#2a2a2a',
        '--toggle-bg': '#1e1e1e',
        '--toggle-border': '#2a2a2a',
        '--success-text': '#DEFF36',
      },
      light: {
        '--accent-color': '#657800',
        '--accent-hover': '#546400',
        '--action-btn-bg': '#657800',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#f8fafc',
        '--header-bg': '#ffffff',
        '--header-border': '#e2e8f0',
        '--sidebar-bg': '#f8fafc',
        '--sidebar-border': '#e2e8f0',
        '--surface-bg': '#ffffff',
        '--surface-border': '#e2e8f0',
        '--input-bg': '#ffffff',
        '--input-border': '#cbd5e1',
        '--badge-bg': '#f1f5f9',
        '--badge-border': '#e2e8f0',
        '--toggle-bg': '#f1f5f9',
        '--toggle-border': '#cbd5e1',
        '--success-text': '#657800',
      },
    },
  },

  ocean: {
    id: 'ocean',
    nameKey: 'themeOceanName',
    nameFallback: 'Ocean',
    isPro: false,
    effect: null,
    preview: {
      accent: '#06b6d4',
      bg: '#0f172a',
      surface: '#1e293b',
      header: '#080e1a',
      sidebar: '#0b1325',
      border: '#334155',
    },
    colors: {
      dark: {
        '--accent-color': '#06b6d4',
        '--accent-hover': '#0891b2',
        '--action-btn-bg': '#06b6d4',
        '--action-btn-text': '#080e1a',
        '--bg-color': '#0f172a',
        '--header-bg': '#080e1a',
        '--header-border': '#1e293b',
        '--sidebar-bg': '#0b1325',
        '--sidebar-border': '#1e293b',
        '--surface-bg': '#1e293b',
        '--surface-border': '#334155',
        '--input-bg': '#0f172a',
        '--input-border': '#334155',
        '--badge-bg': '#1e293b',
        '--badge-border': '#334155',
        '--toggle-bg': '#1e293b',
        '--toggle-border': '#334155',
        '--success-text': '#06b6d4',
      },
      light: {
        '--accent-color': '#0891b2',
        '--accent-hover': '#0e7490',
        '--action-btn-bg': '#0891b2',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#f0f9ff',
        '--header-bg': '#ffffff',
        '--header-border': '#bae6fd',
        '--sidebar-bg': '#f0f9ff',
        '--sidebar-border': '#bae6fd',
        '--surface-bg': '#ffffff',
        '--surface-border': '#bae6fd',
        '--input-bg': '#ffffff',
        '--input-border': '#7dd3fc',
        '--badge-bg': '#e0f2fe',
        '--badge-border': '#bae6fd',
        '--toggle-bg': '#e0f2fe',
        '--toggle-border': '#7dd3fc',
        '--success-text': '#0891b2',
      },
    },
  },

  sunset: {
    id: 'sunset',
    nameKey: 'themeSunsetName',
    nameFallback: 'Sunset',
    isPro: false,
    effect: null,
    preview: {
      accent: '#f97316',
      bg: '#181311',
      surface: '#241c19',
      header: '#0f0b0a',
      sidebar: '#130f0d',
      border: '#3a2e29',
    },
    colors: {
      dark: {
        '--accent-color': '#f97316',
        '--accent-hover': '#ea580c',
        '--action-btn-bg': '#f97316',
        '--action-btn-text': '#0f0b0a',
        '--bg-color': '#181311',
        '--header-bg': '#0f0b0a',
        '--header-border': '#2e231f',
        '--sidebar-bg': '#130f0d',
        '--sidebar-border': '#2e231f',
        '--surface-bg': '#241c19',
        '--surface-border': '#3a2e29',
        '--input-bg': '#181311',
        '--input-border': '#3a2e29',
        '--badge-bg': '#241c19',
        '--badge-border': '#3a2e29',
        '--toggle-bg': '#241c19',
        '--toggle-border': '#3a2e29',
        '--success-text': '#f97316',
      },
      light: {
        '--accent-color': '#c2410c',
        '--accent-hover': '#9a3412',
        '--action-btn-bg': '#c2410c',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#fff7ed',
        '--header-bg': '#ffffff',
        '--header-border': '#fed7aa',
        '--sidebar-bg': '#fff7ed',
        '--sidebar-border': '#fed7aa',
        '--surface-bg': '#ffffff',
        '--surface-border': '#fed7aa',
        '--input-bg': '#ffffff',
        '--input-border': '#fdba74',
        '--badge-bg': '#ffedd5',
        '--badge-border': '#fed7aa',
        '--toggle-bg': '#ffedd5',
        '--toggle-border': '#fdba74',
        '--success-text': '#c2410c',
      },
    },
  },

  violet: {
    id: 'violet',
    nameKey: 'themeVioletName',
    nameFallback: 'Violet',
    isPro: false,
    effect: null,
    preview: {
      accent: '#a855f7',
      bg: '#14111c',
      surface: '#1e1a2b',
      header: '#0c0a12',
      sidebar: '#0f0d16',
      border: '#322b45',
    },
    colors: {
      dark: {
        '--accent-color': '#a855f7',
        '--accent-hover': '#9333ea',
        '--action-btn-bg': '#a855f7',
        '--action-btn-text': '#0c0a12',
        '--bg-color': '#14111c',
        '--header-bg': '#0c0a12',
        '--header-border': '#282238',
        '--sidebar-bg': '#0f0d16',
        '--sidebar-border': '#282238',
        '--surface-bg': '#1e1a2b',
        '--surface-border': '#322b45',
        '--input-bg': '#14111c',
        '--input-border': '#322b45',
        '--badge-bg': '#1e1a2b',
        '--badge-border': '#322b45',
        '--toggle-bg': '#1e1a2b',
        '--toggle-border': '#322b45',
        '--success-text': '#a855f7',
      },
      light: {
        '--accent-color': '#7e22ce',
        '--accent-hover': '#6b21a8',
        '--action-btn-bg': '#7e22ce',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#faf5ff',
        '--header-bg': '#ffffff',
        '--header-border': '#e9d5ff',
        '--sidebar-bg': '#faf5ff',
        '--sidebar-border': '#e9d5ff',
        '--surface-bg': '#ffffff',
        '--surface-border': '#e9d5ff',
        '--input-bg': '#ffffff',
        '--input-border': '#d8b4fe',
        '--badge-bg': '#f3e8ff',
        '--badge-border': '#e9d5ff',
        '--toggle-bg': '#f3e8ff',
        '--toggle-border': '#d8b4fe',
        '--success-text': '#7e22ce',
      },
    },
  },

  rose: {
    id: 'rose',
    nameKey: 'themeRoseName',
    nameFallback: 'Rose',
    isPro: false,
    effect: null,
    preview: {
      accent: '#f43f5e',
      bg: '#181114',
      surface: '#24181d',
      header: '#0f0a0c',
      sidebar: '#130d0f',
      border: '#3b262f',
    },
    colors: {
      dark: {
        '--accent-color': '#f43f5e',
        '--accent-hover': '#e11d48',
        '--action-btn-bg': '#f43f5e',
        '--action-btn-text': '#0f0a0c',
        '--bg-color': '#181114',
        '--header-bg': '#0f0a0c',
        '--header-border': '#301f26',
        '--sidebar-bg': '#130d0f',
        '--sidebar-border': '#301f26',
        '--surface-bg': '#24181d',
        '--surface-border': '#3b262f',
        '--input-bg': '#181114',
        '--input-border': '#3b262f',
        '--badge-bg': '#24181d',
        '--badge-border': '#3b262f',
        '--toggle-bg': '#24181d',
        '--toggle-border': '#3b262f',
        '--success-text': '#f43f5e',
      },
      light: {
        '--accent-color': '#be123c',
        '--accent-hover': '#9f1239',
        '--action-btn-bg': '#be123c',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#fff1f2',
        '--header-bg': '#ffffff',
        '--header-border': '#fecdd3',
        '--sidebar-bg': '#fff1f2',
        '--sidebar-border': '#fecdd3',
        '--surface-bg': '#ffffff',
        '--surface-border': '#fecdd3',
        '--input-bg': '#ffffff',
        '--input-border': '#fda4af',
        '--badge-bg': '#ffe4e6',
        '--badge-border': '#fecdd3',
        '--toggle-bg': '#ffe4e6',
        '--toggle-border': '#fda4af',
        '--success-text': '#be123c',
      },
    },
  },

  // PRO THEMES (10)
  aurora: {
    id: 'aurora',
    nameKey: 'themeAuroraName',
    nameFallback: 'Aurora',
    isPro: true,
    effect: 'shimmer',
    preview: {
      accent: '#10b981',
      bg: '#0a1614',
      surface: '#11221f',
      header: '#050e0c',
      sidebar: '#07110f',
      border: '#1c3832',
    },
    colors: {
      dark: {
        '--accent-color': '#10b981',
        '--accent-hover': '#059669',
        '--action-btn-bg': '#10b981',
        '--action-btn-text': '#050e0c',
        '--bg-color': '#0a1614',
        '--header-bg': '#050e0c',
        '--header-border': '#1c3832',
        '--sidebar-bg': '#07110f',
        '--sidebar-border': '#1c3832',
        '--surface-bg': '#11221f',
        '--surface-border': '#1c3832',
        '--input-bg': '#0a1614',
        '--input-border': '#1c3832',
        '--badge-bg': '#11221f',
        '--badge-border': '#1c3832',
        '--toggle-bg': '#11221f',
        '--toggle-border': '#1c3832',
        '--success-text': '#10b981',
      },
      light: {
        '--accent-color': '#047857',
        '--accent-hover': '#065f46',
        '--action-btn-bg': '#047857',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#ecfdf5',
        '--header-bg': '#ffffff',
        '--header-border': '#a7f3d0',
        '--sidebar-bg': '#ecfdf5',
        '--sidebar-border': '#a7f3d0',
        '--surface-bg': '#ffffff',
        '--surface-border': '#a7f3d0',
        '--input-bg': '#ffffff',
        '--input-border': '#6ee7b7',
        '--badge-bg': '#d1fae5',
        '--badge-border': '#a7f3d0',
        '--toggle-bg': '#d1fae5',
        '--toggle-border': '#6ee7b7',
        '--success-text': '#047857',
      },
    },
  },

  cyber: {
    id: 'cyber',
    nameKey: 'themeCyberName',
    nameFallback: 'Cyber',
    isPro: true,
    effect: 'pulse',
    preview: {
      accent: '#00f0ff',
      bg: '#090e17',
      surface: '#0f1726',
      header: '#04070d',
      sidebar: '#070b12',
      border: '#18253d',
    },
    colors: {
      dark: {
        '--accent-color': '#00f0ff',
        '--accent-hover': '#00c4d4',
        '--action-btn-bg': '#00f0ff',
        '--action-btn-text': '#04070d',
        '--bg-color': '#090e17',
        '--header-bg': '#04070d',
        '--header-border': '#18253d',
        '--sidebar-bg': '#070b12',
        '--sidebar-border': '#18253d',
        '--surface-bg': '#0f1726',
        '--surface-border': '#18253d',
        '--input-bg': '#090e17',
        '--input-border': '#18253d',
        '--badge-bg': '#0f1726',
        '--badge-border': '#18253d',
        '--toggle-bg': '#0f1726',
        '--toggle-border': '#18253d',
        '--success-text': '#00f0ff',
      },
      light: {
        '--accent-color': '#008b99',
        '--accent-hover': '#006c77',
        '--action-btn-bg': '#008b99',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#ecfeff',
        '--header-bg': '#ffffff',
        '--header-border': '#a5f3fc',
        '--sidebar-bg': '#ecfeff',
        '--sidebar-border': '#a5f3fc',
        '--surface-bg': '#ffffff',
        '--surface-border': '#a5f3fc',
        '--input-bg': '#ffffff',
        '--input-border': '#67e8f9',
        '--badge-bg': '#cffafe',
        '--badge-border': '#a5f3fc',
        '--toggle-bg': '#cffafe',
        '--toggle-border': '#67e8f9',
        '--success-text': '#008b99',
      },
    },
  },

  midnight: {
    id: 'midnight',
    nameKey: 'themeMidnightName',
    nameFallback: 'Midnight',
    isPro: true,
    effect: null,
    preview: {
      accent: '#3b82f6',
      bg: '#0c101d',
      surface: '#141a2e',
      header: '#060912',
      sidebar: '#090c17',
      border: '#202a4a',
    },
    colors: {
      dark: {
        '--accent-color': '#3b82f6',
        '--accent-hover': '#2563eb',
        '--action-btn-bg': '#3b82f6',
        '--action-btn-text': '#060912',
        '--bg-color': '#0c101d',
        '--header-bg': '#060912',
        '--header-border': '#202a4a',
        '--sidebar-bg': '#090c17',
        '--sidebar-border': '#202a4a',
        '--surface-bg': '#141a2e',
        '--surface-border': '#202a4a',
        '--input-bg': '#0c101d',
        '--input-border': '#202a4a',
        '--badge-bg': '#141a2e',
        '--badge-border': '#202a4a',
        '--toggle-bg': '#141a2e',
        '--toggle-border': '#202a4a',
        '--success-text': '#3b82f6',
      },
      light: {
        '--accent-color': '#1d4ed8',
        '--accent-hover': '#1e40af',
        '--action-btn-bg': '#1d4ed8',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#eff6ff',
        '--header-bg': '#ffffff',
        '--header-border': '#bfdbfe',
        '--sidebar-bg': '#eff6ff',
        '--sidebar-border': '#bfdbfe',
        '--surface-bg': '#ffffff',
        '--surface-border': '#bfdbfe',
        '--input-bg': '#ffffff',
        '--input-border': '#93c5fd',
        '--badge-bg': '#dbeafe',
        '--badge-border': '#bfdbfe',
        '--toggle-bg': '#dbeafe',
        '--toggle-border': '#93c5fd',
        '--success-text': '#1d4ed8',
      },
    },
  },

  ember: {
    id: 'ember',
    nameKey: 'themeEmberName',
    nameFallback: 'Ember',
    isPro: true,
    effect: 'warmth',
    preview: {
      accent: '#f97316',
      bg: '#170e0a',
      surface: '#261710',
      header: '#0f0805',
      sidebar: '#120b08',
      border: '#3d2419',
    },
    colors: {
      dark: {
        '--accent-color': '#f97316',
        '--accent-hover': '#ea580c',
        '--action-btn-bg': '#f97316',
        '--action-btn-text': '#0f0805',
        '--bg-color': '#170e0a',
        '--header-bg': '#0f0805',
        '--header-border': '#3d2419',
        '--sidebar-bg': '#120b08',
        '--sidebar-border': '#3d2419',
        '--surface-bg': '#261710',
        '--surface-border': '#3d2419',
        '--input-bg': '#170e0a',
        '--input-border': '#3d2419',
        '--badge-bg': '#261710',
        '--badge-border': '#3d2419',
        '--toggle-bg': '#261710',
        '--toggle-border': '#3d2419',
        '--success-text': '#f97316',
      },
      light: {
        '--accent-color': '#c2410c',
        '--accent-hover': '#9a3412',
        '--action-btn-bg': '#c2410c',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#fff7ed',
        '--header-bg': '#ffffff',
        '--header-border': '#fed7aa',
        '--sidebar-bg': '#fff7ed',
        '--sidebar-border': '#fed7aa',
        '--surface-bg': '#ffffff',
        '--surface-border': '#fed7aa',
        '--input-bg': '#ffffff',
        '--input-border': '#fdba74',
        '--badge-bg': '#ffedd5',
        '--badge-border': '#fed7aa',
        '--toggle-bg': '#ffedd5',
        '--toggle-border': '#fdba74',
        '--success-text': '#c2410c',
      },
    },
  },

  arctic: {
    id: 'arctic',
    nameKey: 'themeArcticName',
    nameFallback: 'Arctic',
    isPro: true,
    effect: null,
    preview: {
      accent: '#38bdf8',
      bg: '#0c141c',
      surface: '#13202d',
      header: '#060b10',
      sidebar: '#090e15',
      border: '#1e3347',
    },
    colors: {
      dark: {
        '--accent-color': '#38bdf8',
        '--accent-hover': '#0284c7',
        '--action-btn-bg': '#38bdf8',
        '--action-btn-text': '#060b10',
        '--bg-color': '#0c141c',
        '--header-bg': '#060b10',
        '--header-border': '#1e3347',
        '--sidebar-bg': '#090e15',
        '--sidebar-border': '#1e3347',
        '--surface-bg': '#13202d',
        '--surface-border': '#1e3347',
        '--input-bg': '#0c141c',
        '--input-border': '#1e3347',
        '--badge-bg': '#13202d',
        '--badge-border': '#1e3347',
        '--toggle-bg': '#13202d',
        '--toggle-border': '#1e3347',
        '--success-text': '#38bdf8',
      },
      light: {
        '--accent-color': '#0284c7',
        '--accent-hover': '#0369a1',
        '--action-btn-bg': '#0284c7',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#f0f9ff',
        '--header-bg': '#ffffff',
        '--header-border': '#bae6fd',
        '--sidebar-bg': '#f0f9ff',
        '--sidebar-border': '#bae6fd',
        '--surface-bg': '#ffffff',
        '--surface-border': '#bae6fd',
        '--input-bg': '#ffffff',
        '--input-border': '#7dd3fc',
        '--badge-bg': '#e0f2fe',
        '--badge-border': '#bae6fd',
        '--toggle-bg': '#e0f2fe',
        '--toggle-border': '#7dd3fc',
        '--success-text': '#0284c7',
      },
    },
  },

  graphite: {
    id: 'graphite',
    nameKey: 'themeGraphiteName',
    nameFallback: 'Graphite',
    isPro: true,
    effect: null,
    preview: {
      accent: '#e2e8f0',
      bg: '#111111',
      surface: '#1a1a1a',
      header: '#080808',
      sidebar: '#0c0c0c',
      border: '#2a2a2a',
    },
    colors: {
      dark: {
        '--accent-color': '#e2e8f0',
        '--accent-hover': '#cbd5e1',
        '--action-btn-bg': '#e2e8f0',
        '--action-btn-text': '#080808',
        '--bg-color': '#111111',
        '--header-bg': '#080808',
        '--header-border': '#2a2a2a',
        '--sidebar-bg': '#0c0c0c',
        '--sidebar-border': '#2a2a2a',
        '--surface-bg': '#1a1a1a',
        '--surface-border': '#2a2a2a',
        '--input-bg': '#111111',
        '--input-border': '#2a2a2a',
        '--badge-bg': '#1a1a1a',
        '--badge-border': '#2a2a2a',
        '--toggle-bg': '#1a1a1a',
        '--toggle-border': '#2a2a2a',
        '--success-text': '#e2e8f0',
      },
      light: {
        '--accent-color': '#334155',
        '--accent-hover': '#1e293b',
        '--action-btn-bg': '#334155',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#f1f5f9',
        '--header-bg': '#ffffff',
        '--header-border': '#cbd5e1',
        '--sidebar-bg': '#f1f5f9',
        '--sidebar-border': '#cbd5e1',
        '--surface-bg': '#ffffff',
        '--surface-border': '#cbd5e1',
        '--input-bg': '#ffffff',
        '--input-border': '#94a3b8',
        '--badge-bg': '#e2e8f0',
        '--badge-border': '#cbd5e1',
        '--toggle-bg': '#e2e8f0',
        '--toggle-border': '#94a3b8',
        '--success-text': '#334155',
      },
    },
  },

  amethyst: {
    id: 'amethyst',
    nameKey: 'themeAmethystName',
    nameFallback: 'Amethyst',
    isPro: true,
    effect: null,
    preview: {
      accent: '#c084fc',
      bg: '#150d1e',
      surface: '#221530',
      header: '#0d0713',
      sidebar: '#100918',
      border: '#35204c',
    },
    colors: {
      dark: {
        '--accent-color': '#c084fc',
        '--accent-hover': '#a855f7',
        '--action-btn-bg': '#c084fc',
        '--action-btn-text': '#0d0713',
        '--bg-color': '#150d1e',
        '--header-bg': '#0d0713',
        '--header-border': '#35204c',
        '--sidebar-bg': '#100918',
        '--sidebar-border': '#35204c',
        '--surface-bg': '#221530',
        '--surface-border': '#35204c',
        '--input-bg': '#150d1e',
        '--input-border': '#35204c',
        '--badge-bg': '#221530',
        '--badge-border': '#35204c',
        '--toggle-bg': '#221530',
        '--toggle-border': '#35204c',
        '--success-text': '#c084fc',
      },
      light: {
        '--accent-color': '#7e22ce',
        '--accent-hover': '#6b21a8',
        '--action-btn-bg': '#7e22ce',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#faf5ff',
        '--header-bg': '#ffffff',
        '--header-border': '#e9d5ff',
        '--sidebar-bg': '#faf5ff',
        '--sidebar-border': '#e9d5ff',
        '--surface-bg': '#ffffff',
        '--surface-border': '#e9d5ff',
        '--input-bg': '#ffffff',
        '--input-border': '#d8b4fe',
        '--badge-bg': '#f3e8ff',
        '--badge-border': '#e9d5ff',
        '--toggle-bg': '#f3e8ff',
        '--toggle-border': '#d8b4fe',
        '--success-text': '#7e22ce',
      },
    },
  },

  solar: {
    id: 'solar',
    nameKey: 'themeSolarName',
    nameFallback: 'Solar',
    isPro: true,
    effect: null,
    preview: {
      accent: '#eab308',
      bg: '#171408',
      surface: '#25200c',
      header: '#0e0b04',
      sidebar: '#120e06',
      border: '#3b3213',
    },
    colors: {
      dark: {
        '--accent-color': '#eab308',
        '--accent-hover': '#ca8a04',
        '--action-btn-bg': '#eab308',
        '--action-btn-text': '#0e0b04',
        '--bg-color': '#171408',
        '--header-bg': '#0e0b04',
        '--header-border': '#3b3213',
        '--sidebar-bg': '#120e06',
        '--sidebar-border': '#3b3213',
        '--surface-bg': '#25200c',
        '--surface-border': '#3b3213',
        '--input-bg': '#171408',
        '--input-border': '#3b3213',
        '--badge-bg': '#25200c',
        '--badge-border': '#3b3213',
        '--toggle-bg': '#25200c',
        '--toggle-border': '#3b3213',
        '--success-text': '#eab308',
      },
      light: {
        '--accent-color': '#a16207',
        '--accent-hover': '#854d0e',
        '--action-btn-bg': '#a16207',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#fefce8',
        '--header-bg': '#ffffff',
        '--header-border': '#fef08a',
        '--sidebar-bg': '#fefce8',
        '--sidebar-border': '#fef08a',
        '--surface-bg': '#ffffff',
        '--surface-border': '#fef08a',
        '--input-bg': '#ffffff',
        '--input-border': '#fde047',
        '--badge-bg': '#fef9c3',
        '--badge-border': '#fef08a',
        '--toggle-bg': '#fef9c3',
        '--toggle-border': '#fde047',
        '--success-text': '#a16207',
      },
    },
  },

  forest: {
    id: 'forest',
    nameKey: 'themeForestName',
    nameFallback: 'Forest',
    isPro: true,
    effect: null,
    preview: {
      accent: '#22c55e',
      bg: '#0b160e',
      surface: '#122416',
      header: '#060d07',
      sidebar: '#08110a',
      border: '#1c3b24',
    },
    colors: {
      dark: {
        '--accent-color': '#22c55e',
        '--accent-hover': '#16a34a',
        '--action-btn-bg': '#22c55e',
        '--action-btn-text': '#060d07',
        '--bg-color': '#0b160e',
        '--header-bg': '#060d07',
        '--header-border': '#1c3b24',
        '--sidebar-bg': '#08110a',
        '--sidebar-border': '#1c3b24',
        '--surface-bg': '#122416',
        '--surface-border': '#1c3b24',
        '--input-bg': '#0b160e',
        '--input-border': '#1c3b24',
        '--badge-bg': '#122416',
        '--badge-border': '#1c3b24',
        '--toggle-bg': '#122416',
        '--toggle-border': '#1c3b24',
        '--success-text': '#22c55e',
      },
      light: {
        '--accent-color': '#15803d',
        '--accent-hover': '#166534',
        '--action-btn-bg': '#15803d',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#f0fdf4',
        '--header-bg': '#ffffff',
        '--header-border': '#bbf7d0',
        '--sidebar-bg': '#f0fdf4',
        '--sidebar-border': '#bbf7d0',
        '--surface-bg': '#ffffff',
        '--surface-border': '#bbf7d0',
        '--input-bg': '#ffffff',
        '--input-border': '#86efac',
        '--badge-bg': '#dcfce7',
        '--badge-border': '#bbf7d0',
        '--toggle-bg': '#dcfce7',
        '--toggle-border': '#86efac',
        '--success-text': '#15803d',
      },
    },
  },

  neon: {
    id: 'neon',
    nameKey: 'themeNeonName',
    nameFallback: 'Neon',
    isPro: true,
    effect: 'pulse',
    preview: {
      accent: '#39ff14',
      bg: '#081206',
      surface: '#0f210b',
      header: '#030a02',
      sidebar: '#050e04',
      border: '#193812',
    },
    colors: {
      dark: {
        '--accent-color': '#39ff14',
        '--accent-hover': '#30df10',
        '--action-btn-bg': '#39ff14',
        '--action-btn-text': '#030a02',
        '--bg-color': '#081206',
        '--header-bg': '#030a02',
        '--header-border': '#193812',
        '--sidebar-bg': '#050e04',
        '--sidebar-border': '#193812',
        '--surface-bg': '#0f210b',
        '--surface-border': '#193812',
        '--input-bg': '#081206',
        '--input-border': '#193812',
        '--badge-bg': '#0f210b',
        '--badge-border': '#193812',
        '--toggle-bg': '#0f210b',
        '--toggle-border': '#193812',
        '--success-text': '#39ff14',
      },
      light: {
        '--accent-color': '#2e7d32',
        '--accent-hover': '#1b5e20',
        '--action-btn-bg': '#2e7d32',
        '--action-btn-text': '#ffffff',
        '--bg-color': '#f4fbf3',
        '--header-bg': '#ffffff',
        '--header-border': '#c8e6c9',
        '--sidebar-bg': '#f4fbf3',
        '--sidebar-border': '#c8e6c9',
        '--surface-bg': '#ffffff',
        '--surface-border': '#c8e6c9',
        '--input-bg': '#ffffff',
        '--input-border': '#a5d6a7',
        '--badge-bg': '#e8f5e9',
        '--badge-border': '#c8e6c9',
        '--toggle-bg': '#e8f5e9',
        '--toggle-border': '#a5d6a7',
        '--success-text': '#2e7d32',
      },
    },
  },
};

export const FREE_THEME_KEYS = ['default', 'ocean', 'sunset', 'violet', 'rose'];
export const PRO_THEME_KEYS = [
  'aurora',
  'cyber',
  'midnight',
  'ember',
  'arctic',
  'graphite',
  'amethyst',
  'solar',
  'forest',
  'neon',
];

/**
 * Apply a color theme dynamically to document root element
 * @param {string} themeKey - Key of the color theme
 * @param {'dark'|'light'} mode - Resolved appearance mode ('dark' or 'light')
 */
export function applyColorTheme(themeKey, mode = 'dark') {
  const preset = COLOR_THEMES[themeKey] || COLOR_THEMES.default;
  const themeVars = preset.colors[mode] || preset.colors.dark;

  const root = document.documentElement;
  Object.entries(themeVars).forEach(([varName, varVal]) => {
    root.style.setProperty(varName, varVal);
  });

  // Manage theme animated effect data attribute
  if (preset.effect) {
    root.setAttribute('data-theme-effect', preset.effect);
  } else {
    root.removeAttribute('data-theme-effect');
  }
}
